name: CI/CD - Auth app

on:
  push:
    branches:
      - main
    paths:
      - "apps/auth/**"

defaults:
  run:
    working-directory: apps/auth

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: TypeScript check
        run: pnpm tsc --noEmit

      - name: Run lint
        run: pnpm run lint --max-warnings=0

      - name: Build
        run: pnpm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: apps/auth/dist

  CD:
    needs: CI
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: apps/auth/dist

      - name: Setup AWS cli
        uses: shinyinc/action-aws-cli@1.1

      - name: Deploy on AWS S3 bucket
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/auth

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/auth/mf-manifest.html" "/auth/mf-stats.html" "/auth/@mf-types.d.ts" "/auth/@mf-types.zip"
